# Generated by Django 6.0.5 on 2026-05-18 08:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo', '0004_depositcustomer_depositpickup_depositpickupitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositcustomer',
            old_name='depost_customer_name',
            new_name='deposit_customer_name',
        ),
        migrations.AddField(
            model_name='depositcustomer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
