# Generated by Django 6.0.5 on 2026-05-18 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo', '0005_rename_depost_customer_name_depositcustomer_deposit_customer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositcustomer',
            old_name='deposit_customer_name',
            new_name='full_name',
        ),
    ]
