# Generated by Django 6.0.5 on 2026-05-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo', '0006_rename_deposit_customer_name_depositcustomer_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposittransaction',
            old_name='date',
            new_name='created_at',
        ),
    ]
