# Generated by Django 6.0.5 on 2026-05-25 12:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nyondo", "0010_alter_sale_processed_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depositcustomer",
            name="nin",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="NIN must be 14 characters and start with CM or CF.",
                        regex="^(CM|CF)[A-Z0-9]{12}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="depositcustomer",
            name="phone",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid Ugandan number: 07XXXXXXXXX or +2567XXXXXXXX",
                        regex="^(\\+256|0)7\\d{8}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                choices=[
                    ("BARBED WIRE", "Barbed Wire"),
                    ("CEMENT", "Cement"),
                    ("IRON SHEET", "Iron Sheet"),
                    ("NAILS", "Nails"),
                    ("WHEELBARROW", "Wheelbarrow"),
                    ("WIRE MESH", "Wire Mesh"),
                    ("IRON BARS", "Iron Bars"),
                ],
                on_delete=django.db.models.deletion.PROTECT,
                to="nyondo.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("PIECE", "Piece"),
                    ("KILOGRAM", "Kilogram"),
                    ("BAG", "Bag"),
                    ("METER", "Meter"),
                    ("ROLL", "Roll"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="stockentry",
            name="product",
            field=models.ForeignKey(
                choices=[
                    ("1 inc", "1 inc"),
                    ("3 inc", "3 inc"),
                    ("4 inc", "4 inc"),
                    ("5 inc", "5 inc"),
                    ("CEM IIIN", "CEM IIIN"),
                    ("CEM IIN", "CEM IIN"),
                    ("High tensile", "High tensile"),
                    ("Low tensile", "Low tensile"),
                    ("Roofing nails", "Roofing nails"),
                    ("Wheelbarrows", "Wheelbarrows"),
                    ("Wire mesh", "Wire mesh"),
                ],
                on_delete=django.db.models.deletion.PROTECT,
                to="nyondo.product",
            ),
        ),
    ]
